server:
  port: 8500
spring:
  application:
    name: yang-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YangQiang-G/yang10-config.git      # 仓库地址
          search-paths: yang10-config-center  # 仓库下的子目录
          username: YangQiang-G  # GitHub用户名
          password: 2235674170@qq.com  # GitHub密码
